using System.Text;

namespace Cex;

public partial class CodeGenerator
{
    private string BuildOutput()
    {
        var sb = new StringBuilder();
        sb.AppendLine("; Generated by C! compiler");
        sb.AppendLine("extern ExitProcess");
        sb.AppendLine("extern WriteConsoleA");
        sb.AppendLine("extern GetStdHandle");
        sb.AppendLine("extern ReadConsoleA");
        sb.AppendLine();
        sb.AppendLine("section .data"); sb.Append(_data); sb.AppendLine();
        sb.AppendLine("section .bss");  sb.Append(_bss);  sb.AppendLine();
        sb.AppendLine("section .text");
        sb.AppendLine("global start");
        sb.AppendLine("start:");
        sb.Append(_main); sb.AppendLine();
        sb.Append(_helpers);
        return sb.ToString();
    }
}